Repository AY2425S1-CS2103T-T15-1/tp, pull requests merged in 2024-10, with the labels that each got.

#51 Update User Story
  docs/DeveloperGuide.md
Labels: type.Task

#64 Add rental information with relevant classes and JUnit tests
  src/main/java/seedu/address/commons/util/RentalUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/rentalinformation/Address.java
  src/main/java/seedu/address/model/rentalinformation/CustomerList.java
  src/main/java/seedu/address/model/rentalinformation/Deposit.java
  src/main/java/seedu/address/model/rentalinformation/MonthlyRent.java
  src/main/java/seedu/address/model/rentalinformation/RentDueDate.java
  src/main/java/seedu/address/model/rentalinformation/RentalDate.java
  src/main/java/seedu/address/model/rentalinformation/RentalInformation.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/commons/util/RentalUtilTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/rentalinformation/AddressTest.java
  src/test/java/seedu/address/model/rentalinformation/CustomerListTest.java
  src/test/java/seedu/address/model/rentalinformation/DepositTest.java
  src/test/java/seedu/address/model/rentalinformation/MonthlyRentTest.java
  src/test/java/seedu/address/model/rentalinformation/RentDueDateTest.java
  src/test/java/seedu/address/model/rentalinformation/RentalDateTest.java
  src/test/java/seedu/address/model/rentalinformation/RentalInformationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#69 Resolve merge conflict
  src/main/java/seedu/address/model/client/Address.java
  src/main/java/seedu/address/model/rentalinformation/Address.java
  src/test/java/seedu/address/model/client/AddressTest.java
  src/test/java/seedu/address/model/rentalinformation/AddressTest.java
Labels: priority.High

#73 Link RentalInformation to Client
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddRentalCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddRentalCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/rentalinformation/Address.java
  src/main/java/seedu/address/model/rentalinformation/RentalInformation.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRentalInformation.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
Labels: priority.High

#84 Fix branch conflict
  src/main/java/seedu/address/ui/RentalInformationCard.java
  src/main/java/seedu/address/ui/RentalInformationListPanel.java
Labels: priority.High

#82 Add functionality for FindCommandParser to search by email or phone
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/client/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/PhoneContainsKeywordsPredicate.java
Labels: priority.High

#102 Add redit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddRentalCommand.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/EditRentalCommand.java
  src/main/java/seedu/address/logic/parser/AddRentalCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditRentalCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#109 Modify FindCommand to support searching in email and phone fields
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: priority.High

#106 Update Checkstyle Line Separator
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddRentalCommandParser.java
  src/main/java/seedu/address/logic/parser/EditClientCommandParser.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/true_rental.jpg
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditClientCommandParserTest.java
Labels: priority.High

#117 Fix merge error
  src/main/java/seedu/address/logic/commands/EditRentalCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditRentalCommandTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#126 Implement UI for rental information list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ViewRentalCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RentalInformationCard.java
  src/main/java/seedu/address/ui/RentalInformationListPanel.java
  src/main/resources/view/RentalInformationCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRentalCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High

#131 Add UI update
  src/main/java/seedu/address/logic/commands/DeleteRentalCommand.java
  src/main/java/seedu/address/logic/commands/EditRentalCommand.java
  src/main/java/seedu/address/ui/RentalInformationListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RentalInformationListPanel.fxml
Labels: priority.High

#132 Remove rental information list in client list
  src/main/java/seedu/address/logic/commands/AddRentalCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRentalCommand.java
  src/main/java/seedu/address/logic/commands/EditRentalCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddRentalCommandTest.java
Labels: severity.VeryLow

#134 Modify Find Command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/PhoneContainsKeywordsPredicate.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#143 Update UserGuide.md
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/client/Client.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.High

#147 Update Client Add and Find Function
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/client/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/RentalInformationContainsKeywordsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
Labels: priority.High

#160 Add more JUnit tests
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#158 Add simple auto complete feature
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Epic, priority.Medium

#164 Resolve merge conflict
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.High

#166 Fix integration bug for command history and auto complete
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug, priority.High

#162 Enable Assertions
  build.gradle
Labels: priority.High

#155 Add predicate tests
  src/main/java/seedu/address/model/rentalinformation/Address.java
  src/test/java/seedu/address/model/client/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/client/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/client/RentalInformationContainsKeywordsPredicateTest.java
Labels: priority.Medium

#169 Change radd to have optional parameters
  src/main/java/seedu/address/logic/commands/AddRentalCommand.java
  src/main/java/seedu/address/logic/parser/AddRentalCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/rentalinformation/CustomerList.java
  src/main/java/seedu/address/model/rentalinformation/Deposit.java
  src/main/java/seedu/address/model/rentalinformation/MonthlyRent.java
  src/main/java/seedu/address/model/rentalinformation/RentDueDate.java
  src/main/java/seedu/address/model/rentalinformation/RentalDate.java
  src/main/java/seedu/address/model/rentalinformation/RentalInformation.java
  src/main/java/seedu/address/storage/JsonAdaptedRentalInformation.java
  src/test/java/seedu/address/logic/commands/AddRentalDescriptorTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditRentalCommandTest.java
  src/test/java/seedu/address/logic/commands/EditRentalDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddRentalCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditRentalCommandParserTest.java
  src/test/java/seedu/address/model/rentalinformation/AddressTest.java
  src/test/java/seedu/address/model/rentalinformation/CustomerListTest.java
  src/test/java/seedu/address/model/rentalinformation/DepositTest.java
  src/test/java/seedu/address/model/rentalinformation/MonthlyRentTest.java
  src/test/java/seedu/address/model/rentalinformation/RentDueDateTest.java
  src/test/java/seedu/address/model/rentalinformation/RentalDateTest.java
  src/test/java/seedu/address/model/rentalinformation/RentalInformationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRentalInformationTest.java
  src/test/java/seedu/address/testutil/AddRentalDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditRentalDescriptorBuilder.java
Labels: type.Epic, type.Enhancement, priority.High

#174 Add abstraction for AddRentalCommandParser and EditRentalCommandParser
  src/main/java/seedu/address/logic/commands/AddRentalCommand.java
  src/main/java/seedu/address/logic/commands/EditRentalCommand.java
  src/main/java/seedu/address/logic/parser/AddRentalCommandParser.java
  src/main/java/seedu/address/logic/parser/EditRentalCommandParser.java
Labels: type.Enhancement, priority.High

#171 Update UML for ModelClassDiagram and StorageClassDiagram
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Enhancement

#176 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddClientSequenceDiagram.puml
  src/main/java/seedu/address/storage/CommandHistoryStorage.java
Labels: priority.High

#181 Add Test
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#189 Standardise naming scheme for `PersonListCard` and `RentalInformationListCard`
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/ui/PersonListCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/RentalInformationListCard.java
  src/main/java/seedu/address/ui/RentalInformationListPanel.java
Labels: severity.Medium
