Repository AY2425S1-CS2103T-T15-1/tp, pull requests merged in 2024-11, with the labels that each got.

#193 Update keyword list
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Enhancement

#205 Update 'UI component' section of the DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Medium

#214 Update DG
  docs/DeveloperGuide.md
  docs/images/defaultUi.png
  docs/images/uiWithDescription.png
Labels: priority.High

#191 Update UG
  docs/SettingUp.md
  docs/UserGuide.md
  docs/images/img.png
Labels: type.Enhancement

#184 Implement sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRentalCommandTest.java
  src/test/java/seedu/address/logic/commands/NextCommandHistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/PreviousCommandHistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium

#209 Update UG
  docs/UserGuide.md
Labels: priority.High

#220 Update SortCommand message
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: priority.Medium

#217 Update UI
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/ui/PersonListCard.java
Labels: priority.High, alpha-bug

#236 Update Ui
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRentalCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RentalInformationListPanel.fxml
  src/test/java/seedu/address/logic/commands/ViewRentalCommandTest.java
Labels: priority.Medium, alpha-bug

#242 Update UG
  docs/UserGuide.md
  docs/images/caddUi.png
  docs/images/ceditUi.png
  docs/images/findUi.png
  docs/images/helpMessage.png
  docs/images/listUi.png
  docs/images/rviewUi.png
  docs/index.md
Labels: priority.High

#235 Update `equals()` in `ModelManager` and fix integration tests that were affected
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/CommandHistoryStorage.java
  src/test/java/seedu/address/logic/commands/DeleteRentalCommandTest.java
  src/test/java/seedu/address/logic/commands/EditRentalCommandTest.java
  src/test/java/seedu/address/storage/CommandHistoryStorageTest.java
Labels: severity.High, alpha-bug

#239 Update UI colors for command input and output messages
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/Extensions.css
Labels: priority.Medium

#244 Modify Sample Data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.High, alpha-bug

#253 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement

#257 Fix incorrect image paths
  docs/UserGuide.md
Labels: severity.High

#260 Update UG
  docs/UserGuide.md
Labels: priority.High

#265 Fix YAML frontmatter indentation errors in docs
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/Testing.md
  docs/UserGuide.md
  docs/index.md
Labels: severity.VeryLow

#266 Update Message
  src/main/java/seedu/address/logic/commands/NextCommandHistoryCommand.java
  src/main/java/seedu/address/logic/commands/PreviousCommandHistoryCommand.java
Labels: priority.Low, alpha-bug

#268 Update DG for redit, radd and autofill
  docs/DeveloperGuide.md
Labels: type.Enhancement

#274 Update UG
  docs/UserGuide.md
  docs/images/raddUi.png
  docs/images/reditUi.png
Labels: type.Enhancement

#271 Update DG
  docs/DeveloperGuide.md
  docs/images/true_rental.jpg
Labels: priority.Medium

#259 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/sortUi.png
Labels: priority.High

#255 Add comparators for sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High, alpha-bug

#275 Update UG
  docs/UserGuide.md
Labels: type.Enhancement

#370 Fix UG bug
  docs/UserGuide.md
Labels: update-ug

#371 Fix duplicate bug
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/Phone.java
  src/test/java/seedu/address/model/client/EmailTest.java
  src/test/java/seedu/address/model/client/PhoneTest.java
Labels: type.Bug, severity.High

#372 Branch v1.6 update ug fix tag overflow
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: update-ug

#375 Fix Bug
  src/main/java/seedu/address/model/client/RentalInformationContainsKeywordsPredicate.java
Labels: type.Bug, severity.High

#378 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/caddUi.png
  docs/images/cdeleteUi1.png
  docs/images/cdeleteUi2.png
  docs/images/ceditUi.png
  docs/images/findUi.png
  docs/images/helpButton.png
  docs/images/listUi.png
  docs/images/raddUi.png
  docs/images/reditUi.png
  docs/images/rviewUi.png
  docs/images/uiWithDescription.png
Labels: priority.High, update-ug

#379 Update UG
  docs/UserGuide.md
Labels: update-ug

#380 Update UG
  docs/UserGuide.md
Labels: update-ug

#377 Update use case, basic usage for sort, add UI image to UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.Low, update-ug, update-dg

#373 Update UG/DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: update-ug, update-dg

#376 Update UG/DG to include fix SortCommand comparator to ignore case as a planned enhancement/known issue
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.Medium, update-ug, update-dg

#381 Update UG DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/true_rental.jpg
Labels: priority.High

#382 Update UG and DG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: update-ug, update-dg

#383 Update UG DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#384 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: update-ug, update-dg

#386 Update UG
  docs/UserGuide.md
Labels: update-ug

#393 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: update-ug, update-dg

#392 Update UG
  docs/UserGuide.md
Labels: update-ug

#394 Update UG
  docs/UserGuide.md
  docs/images/img.png
  docs/images/sortUi.png
Labels: priority.High

#391 Format 'Use cases' section in DG
  docs/DeveloperGuide.md
Labels: severity.VeryLow, update-dg, formatting.error
